config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  root to: "pages#home"

  resources :users do
    resources :follows, only: %i[create]

    member do
      get :chat
    end
  end

  resources :messages, only: %i[create]
  resources :user_sport_interests, only: %i[index new create edit update destroy]

  resources :follows, only: %i[destroy]

  resources :events, only: %i[index show new create edit update] do
    member do
      patch :cancel_event
      get :payment
      post :success
      get :confirmation
      get :calendar

    end

    resources :comments, only: %i[create]

    resources :participations, only: %i[new create]
  end

  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  resources :participations, only: %i[index show edit update] do
    member do
      patch :cancel_participation
      patch :refund
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :event, optional: true

  broadcasts_to ->(notification) { "notifications_user_#{notification.recipient_id}" }, inserts_by: :prepend
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def mark_as_read
    current_user.received_notifications.where(read: false).update_all(read: true)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "notification_badge",
          partial: "notifications/badge",
          locals: { unread_count: 0 }
        )
      end
      format.html { head :ok }
    end
  end
end

app/views/notifications/_badge.html.erb
<% if unread_count > 0 %>
  <span class="badge"><%= unread_count %></span>
<% end %>

app/views/notifications/_notification.html.erb
<turbo-frame id="notification_<%= notification.id %>">
  <div class="notification <%= "unread" unless notification.read %>">
    <% case notification.action %>
    <% when "created_event" %>
      <%= link_to "#{notification.actor.first_name} created a new event: #{notification.event.title}", event_path(notification.event), data: { turbo: false } %>
    <% when "joined_event" %>
      <%= link_to "#{notification.actor.first_name} joined the event: #{notification.event.title}", event_path(notification.event), data: { turbo: false } %>
    <% when "cancelled_event" %>
      <%= "#{notification.actor.first_name} cancelled their event: #{notification.event.title}" %>
    <% when "followed_you" %>
      <%= link_to "#{notification.actor.first_name} just followed you", user_path(notification.actor), data: { turbo: false } %>
    <% when "message_sent" %>
      <%= link_to "#{notification.actor.first_name} #{notification.actor.last_name} just sent you a message.", chat_user_path(notification.actor), data: { turbo: false } %>
    <% end %>
  </div>
</turbo-frame>