config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  root to: "pages#home"

  resources :users do
    resources :follows, only: %i[create]

    member do
      get :chat
    end
  end

  resources :messages, only: %i[create]
  resources :user_sport_interests, only: %i[index new create edit update destroy]

  resources :follows, only: %i[destroy]

  resources :events, only: %i[index show new create edit update] do
    member do
      patch :cancel_event
      get :payment
      post :success
      get :confirmation
      get :calendar

    end

    resources :comments, only: %i[create]

    resources :participations, only: %i[new create]
  end

  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  resources :participations, only: %i[index show edit update] do
    member do
      patch :cancel_participation
      patch :refund
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :participations, dependent: :destroy
  has_many :events, through: :participations
  has_many :created_events, class_name: "Event", foreign_key: "user_id", dependent: :destroy
  has_many :user_sport_interests, dependent: :destroy
  has_many :sports, through: :user_sport_interests

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_follows, source: :followed

  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower

  has_many :received_notifications, class_name: "Notification", foreign_key: "recipient_id", dependent: :destroy
  has_many :sent_notifications, class_name: "Notification", foreign_key: "actor_id", dependent: :nullify

  has_many :comments, dependent: :destroy

  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id", dependent: :destroy
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id", dependent: :destroy

  has_one_attached :avatar

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  skip_before_action :authenticate_user!

  def google_oauth2
    user = User.from_omniauth(auth)
    user.save if user.new_record? # Save the user if it's a new record
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_sport_interest = UserSportInterest.new
  end

  def chat
    @user = User.find(params[:id])

    @messages = Message.where(
      "(sender_id = :current AND recipient_id = :other) OR (sender_id = :other AND recipient_id = :current)",
      current: current_user.id,
      other: @user.id
    ).order(created_at: :asc)

    @new_message = Message.new
  end
end

app/views/users/chat.html.erb
<%= turbo_stream_from "chat_#{[current_user.id, @user.id].sort.join("_")}" %>

<div id="messages">
  <%= render @messages, current_user_id: current_user.id %>
</div>

<%= form_with model: @new_message, url: messages_path,
  data: { controller: "reset-form",
  action: "turbo:submit-end->reset-form#reset" } do |f| %>
  <%= f.hidden_field :recipient_id, value: @user.id %>
  <%= f.text_area :content, placeholder: "Write a message..." %>
  <%= f.submit "Send" %>
<% end %>

app/views/users/show.html.erb
<div class="container mt-4">
    <h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
    <p><%= @user.bio %></p>

  <div class="row">
    <div class="col-8">
  <% if @user.user_sport_interests.any? %>
    <% @user.user_sport_interests.each do |interest| %>
      <div class="p-3 mb-3">
        <div class="d-flex justify-content-between align-items-center mb-1">
        </div>
        <%# <%= image_tag  %>
        <% sport = interest.sport %>
        <div class="form">
          <%= image_tag "#{sport.icon}" , style: "width: 50px; height: 50px;" %>
          <%= simple_form_for interest do |f| %>
            <div class="form-inputs row justify-content-center">
              <%= f.input :skill_level, collection: UserSportInterest::SKILL_LEVELS, prompt: "Select your skill level" %>
            </div>
            <%= f.submit "Save changes", class: "shining-button px-4 py-2 mb-3" %>
            <%= link_to "Delete", user_sport_interest_path(interest), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                class: "shining-button alert-color-background px-4 py-2" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h5 class="mt-4">There are no interests yet.</h5>
  <% end %>
    </div>
    <div class="col-4">

    <div class="container">
    <% if @user == current_user %>
      <div class="user_sport_interests-form">
        <div class="mt-2">
          <%= render "user_sport_interests/form", user_sport_interest: @user_sport_interest %>
        </div>
      </div>
    </div>

    </div>
    </div>

  </div>



    <% else %>

      <div class="d-flex justify-content-start align-items-center gap-2">
        <% unless current_user.following.include?(@user) %>
          <%= button_to "Follow him", user_follows_path(@user) , method: :post, class: "simple-primary-button" %>
        <% else %>
          <%= button_to "Unfollow him", follow_path(current_user.active_follows.find_by(followed_id: @user.id)), method: :delete, class: "simple-primary-button" %>
        <% end %>
        <%= link_to "Chat with #{@user.first_name} #{@user.last_name}", chat_user_path(@user), class: "simple-primary-button" %>
      </div>
    <% end %>
  </div>
</div>