config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
      controllers: {
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  root to: "pages#home"

  resources :users do
    resources :follows, only: %i[create]

    member do
      get :chat
    end
  end

  resources :messages, only: %i[create]
  resources :user_sport_interests, only: %i[index new create edit update destroy]

  resources :follows, only: %i[destroy]

  resources :events, only: %i[index show new create edit update] do
    member do
      patch :cancel_event
      get :payment
      post :success
      get :confirmation
      get :calendar

    end

    resources :comments, only: %i[create]

    resources :participations, only: %i[new create]
  end

  resources :notifications, only: [] do
    collection do
      patch :mark_as_read
    end
  end

  resources :participations, only: %i[index show edit update] do
    member do
      patch :cancel_participation
      patch :refund
    end
  end
end

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap align-items-center py-3 my-4 border-top justify-content-between">

<div class="row align-items-center justify-content-between">
 <div class="col-md-9">
          <h3>Sportsmate</h3>
          <h5>The ultimate all-in-one platform for every player, coach and club.</h5>
          <%= link_to "Discover events", events_path, class: "shining-button px-4 py-2" %>
          <%= link_to "About us", root_path, class: "shining-button px-4 py-2" %>
  </div>

</div>

  <div class="col-md-3 d-flex justify-content-end footer-links gap-2">
    <a href="#"><i class="fab fa-github" style="color: black;"></i></a>
    <a href="#"><i class="fab fa-instagram" style="color: #E4405F;"></i></a>
    <a href="#"><i class="fab fa-facebook" style="color: #1877F2;"></i></a>
    <a href="#"><i class="fab fa-twitter" style="color: #1DA1F2;"></i></a>
    <a href="#"><i class="fab fa-linkedin" style="color: #0A66C2;"></i></a>
  </div>

  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-light mb-3">
  <div class="container-fluid d-flex align-items-center justify-content-between">

    <%= link_to root_path, class: "navbar-brand me-3" do %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
    <% end %>

    <% unless controller_name == "sessions" || controller_name == "registrations" || action_name == "new" || action_name == "create" || action_name == "edit" || action_name == "update" %>
      <%= form_with url: events_path, method: :get, local: true, class: "search-form rounded-pill d-flex align-items-center shadow-sm px-5 py-1 bg-light me-auto w-auto", style: "" do |f| %>
        <div class="d-flex align-items-center me-3">
          <%= f.text_field :query,
                value: params[:query],
                placeholder: "Search for events",
                class: "form-control border-0 bg-transparent shadow-none",
                style: "width: auto;" %>
        </div>

        <div class="vr mx-2"></div>

        <div class="d-flex align-items-center me-3">
          <i class="fa-solid fa-location-dot"></i>
          <%= f.text_field :location,
                value: params[:location],
                placeholder: "Location",
                class: "form-control border-0 bg-transparent shadow-none",
                style: "width: auto;" %>
        </div>

        <%= button_tag type: "submit", class: "btn simple-primary-button rounded-circle d-flex align-items-center justify-content-center", style: "width: 40px; height: 40px;" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <li class="nav-item m-top-2">
            <%= link_to "New event", new_event_path, class: "simple-primary-button me-2" %>
          </li>

          <div data-controller="notifications"
            data-notifications-url-value="<%= mark_as_read_notifications_path %>">

            <button class="notification-bell mx-3 mt-1"
              data-action="click->notifications#markAsRead"
              data-bs-toggle="dropdown"
              aria-expanded="false">
              🛎️
              <%= turbo_frame_tag "notifications_badge" do %>
                <% unread_count = current_user.received_notifications.where(read: false).count %>
                <%= render "notifications/badge", unread_count: unread_count %>
              <% end %>
            </button>

              <div class="dropdown-menu dropdown-menu-end p-2" style="min-width: 300px;">
                <%= turbo_stream_from "notifications_user_#{current_user.id}" %>

                <% current_user.received_notifications.order(created_at: :desc).limit(10).each do |notification| %>
                  <%= render "notifications/notification", notification: notification %>
                <% end %>

              </div>
            </div>

          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "avatar rounded-circle", alt: "dropdown menu", style: "width: 30px; height: 30px;" %>
              <% else %>
                <%= image_tag "default_avatar.png", class: "avatar rounded-circle", alt: "dropdown menu", style: "width: 30px; height: 30px;" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My events", participations_path, class: "dropdown-item" %>
              <%= link_to "Profile", current_user, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "simple-primary-button me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "simple-primary-button outline me-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>